### ISSUE TITLE
fails to detect grpcio requirement

### ISSUE THREAD

**Issue by wwuck** [Arkq/flake8-requirements#10]
`flake8-requirements` gives an incorrect `I900` linting error when the [grpcio](https://pypi.org/project/grpcio/) package is used in code, as the package name on pypi does not match the import name.

```
$ cat requirements.txt 
grpcio

$ cat test.py 
import grpc
status = grpc.StatusCode.UNKNOWN

$ flake8
./test.py:1:1: I900 'grpc' not listed as a requirement
```

**Comment by wwuck** [comment]
Hi @Arkq 

This is working fine for `grpcio` but appears to be failing for `grpcio-health-checking`.

**Comment by Arkq** [comment]
Thx, for reporting. Right now it should work fine :)
