### ISSUE TITLE
Incorrect parsing of comment lines following a line continuation

### ISSUE THREAD

**Issue by wwuck** [Arkq/flake8-requirements#14]
According to the newly released [requirements file format spec](https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format):

- A line that begins with # is treated as a comment and ignored.
- A line ending in an unescaped \ is treated as a line continuation and the newline following it is effectively ignored.
- Comments are stripped before line continuations are processed.

If a line with a line continuation is followed immediately by a comment line, then the comment line will get ignored and the following non-comment line will be appended erroneously onto the previous line.

E.g.
```
joblib==0.14.1 \
    --hash=sha256:0630eea4f5664c463f23fbf5dcfc54a2bc6168902719fa8e19daf033022786c8 \
    --hash=sha256:bdb4fd9b72915ffb49fde2229ce482dd7ae79d842ed8c2b4c932441495af1403 \
    # via scikit-learn
numpy==1.18.1 \
    --hash=sha256:1786a08236f2c92ae0e70423c45e1e62788ed33028f94ca99c4df03f5be6b3c6
```

is incorrectly converted into

```
joblib==0.14.1 --hash=sha256:0630eea4f5664c463f23fbf5dcfc54a2bc6168902719fa8e19daf033022786c8 --hash=sha256:bdb4fd9b72915ffb49fde2229ce482dd7ae79d842ed8c2b4c932441495af1403 numpy==1.18.1 --hash=sha256:1786a08236f2c92ae0e70423c45e1e62788ed33028f94ca99c4df03f5be6b3c6
```

**Comment by Arkq** [comment]
> Comments are stripped before line continuations are processed.

Are you sure that your example is not erroneous? Because according to the order of actions, if comment lines are stripped before line continuations, then hanging line continuation will join next line.... Current `joinlines()` implementation also does not yield line if line continuation is not followed by `\n` at the end of file. I thought that such cases are not correct `requirements.txt` :/

**Comment by Arkq** [comment]
I think that even PIP does not parse the requirements.txt file according to spec. If you mix line continuations and comment lines, first appearing comment line stops pip from reading next line e.g. --hash option which is under the comment line....

What a mess :D

**Comment by wwuck** [comment]
I think I can solve this by fixing `pip-compile` from pip-tools to not output the trailing line continuation before the generated comment.  This will allow `joinlines()` to do a first-pass strip of comments before continuing on to process the remaining requirements lines.
