### ISSUE TITLE
False positive for `ntpath` and `posixpath` standard library modules

### ISSUE THREAD

**Issue by dylan-kerr** [Arkq/flake8-requirements#18]
If my code imports the `ntpath` or `posixpath` modules from the standard library, flake8-requirements will complain that they are not listed as a requirement. This appears to be because they are not listed in `STDLIB_PY3` (or `STDLIB_PY2`, for that matter) in `src/flake8_requirements/modules.py`.

Before I put in a pull request to add those modules to the list, I just wanted to check if this was an intentional omission - is there any reason these modules should not be considered a part of the standard library?

**Comment by Arkq** [comment]
If these modules are part of standard libraries, then it was omission :)
