### ISSUE TITLE
False positive for dateutil

### ISSUE THREAD

**Issue by labrys** [Arkq/flake8-requirements#2]
Receiving a false positive for `I900 'dateutil' not listed as a requirement`.

**Comment by labrys** [comment]
As a side note, would it be possible to add a config option to add custom mappings?

**Comment by Arkq** [comment]
Custom mapping is possible, but the syntax is horrible, so it is not
documented... :P When I get back on my laptop, I'll try to think of some
better way of providing custom mappings, or simply document the current one.

P.S. thx for the PR, I will merge it later (I'm on the phone right now)
