### ISSUE TITLE
Support requirements.txt files which delegate to setup.py

### ISSUE THREAD

**Issue by mje-nz** [Arkq/flake8-requirements#26]
In a library, it's convenient to use `requirements.txt` to specify dev dependencies and then add a requirement of `.` or `-e .` to install the library with `setup.py`. It would be good if flake8-requirements supported this, rather than defaulting to the requirements from `setup.py` when both files are present.

**Comment by Arkq** [comment]
I've added command line option ``--requirements-file=FILE`` which shall be used to specify requirements text file (for more info see README). When specified it will take precedence over `setup.py`.
