### ISSUE TITLE
Unable to use with requirements in sub-folders

### ISSUE THREAD

**Issue by philjnicholls** [Arkq/flake8-requirements#28]
My project uses the common pattern of:

+-- requirements.txt
+-- requirements
|   +-- common.txt
|   +-- production.txt
|   +-- test.txt
|   +-- development.txt

requirements.txt includes production.txt which in turn includes common.txt.

When I run flake8 all my requirements show up as I900 Not listed as a requirement.

It seems that resolve_requirement won't handle -r includes with a relative path which I think is necessary for pip to be happy.

So the app finds requirements.txt, includes production.txt thanks to '-r requirements/production.txt' but fails when trying to include common.txt as the line from production.txt is '-r common.txt'.

Am I missing something or is this something you'd be happy for me to work on a PR for?

**Comment by Arkq** [comment]
> Am I missing something or is this something you'd be happy for me to work
on a PR for?

If you 've got an idea how to resolve this problem, please make a PR. PR is
always appreciated :)
