### ISSUE TITLE
Support arbitrary requirements files

### ISSUE THREAD

**Issue by Dreamsorcerer** [Arkq/flake8-requirements#33]
It would be good to have a config argument that allows specifying where the requirements files are (a simple glob pattern would work for most cases).

As an example, for the aiohttp project: https://github.com/aio-libs/aiohttp/tree/master/requirements
This would work if a simple pattern could be added to the config like `requirements/*` or `requirements/*.txt`.

Also worth noting that it doesn't pick these up from setup.py if read dynamically, like:
```
def read_requirements(path: str) -> List[str]:
    file_path = pathlib.Path(__file__).parent / path
    with open(file_path) as f:
        return f.read().split("\n")

setup(
    ...
    install_requires=read_requirements("requirements/production.txt"),
)
```

**Comment by Arkq** [comment]
I've added command line option ``--requirements-file``. It's not based on glob pattern, but I hope it will suites you.

**Comment by Dreamsorcerer** [comment]
Works nicely with a `requirements-dev.txt` file (which has a `-r requirements.txt`), thanks.
