### ISSUE TITLE
Change to pep517.meta.load

### ISSUE THREAD

**Issue by wwuck** [Arkq/flake8-requirements#39]
Should this plugin change to using [pep517.meta.load](https://github.com/pypa/pep517/blob/dc1192dd7cf7f9d2a295a3f1f1c93ab659f8556b/pep517/meta.py#L62-L72)? I've tried to change from setup.py to setup.cfg for project metadata and this plugin doesn't detect install_requires metadata in setup.cfg.

ref: https://github.com/pypa/setuptools/issues/1951#issuecomment-722645440

**Comment by Arkq** [comment]
There is one problem with using `pep517.meta.load`. Firstly, it's not a public API of `pep517` module. Secondly, it seems that it requires `pip` to be available. I think that for now I can add built-in support for requirements from `setup.cfg` file. Do you have any edge cases for `install_requires` section in setup.cfg? Because from the documentation, it seems that the syntax is rather simple: https://setuptools.readthedocs.io/en/latest/userguide/declarative_config.html

**Comment by Arkq** [comment]
@wwuck could you please check whether PR #40 will work for you?

**Comment by wwuck** [comment]
@Arkq I can confirm that PR #40 works with setup.cfg.  Thanks!

My other thought behind using `pep517.meta.load` was that it would also support PEP621 (either currently or in the future, haven't checked this).
Now that I've looked further, I see that `pep517.meta.load` will possibly be deprecated/removed soon (https://github.com/pypa/pep517/issues/100), but there might be an alternative appearing out of that discussion https://github.com/pypa/build/issues/181.  It looks like that might be the way to go when it finally gets implemented?

It would be nice to have support for projects using PEP621 `pyproject.toml` configuration as well and I'm guessing using something common like that proposed feature of pypa/build would get PEP621 support included automatically?

**Comment by Arkq** [comment]
> It would be nice to have support for projects using PEP621 pyproject.toml configuration (eg. flit) as well and I'm guessing using something common like that proposed feature of pypa/build would get PEP621 support included automatically?

Yes, that would be nice to have a separate module for querying requirements. If there will be such used by other tools, I will jump the bandwagon as well.

**Comment by wwuck** [comment]
@Arkq Does this do the job?

https://github.com/pypa/build/issues/301
