### ISSUE TITLE
False positive for Upper case in project name

### ISSUE THREAD

**Issue by tovmeod** [Arkq/flake8-requirements#4]
I have a project which defines its name in setup.py.

In checker.py: 342 it gets the setup.py name and passes to project2module which lowercases the name.

For some reason my project uses a uppercase as the first letter of the folder name, meaning imports from inside the project is from Project.utils import foo

so the checker yield I900

**Comment by Arkq** [comment]
In most cases (standard libraries) the include path is all-lowercase and hyphen converted to underscore (hence heuristic in `checker.py:342`). However, there are cases where such conversion is incorrect. Fot that reason there is a [mapping with exceptions](https://github.com/Arkq/flake8-requirements/blob/master/src/flake8_requirements/modules.py#L493). For custom project, you have to define such mapping in the `setup.cfg`. See [customization](https://github.com/Arkq/flake8-requirements#customization) section in README.

**Comment by tovmeod** [comment]
I managed to make this work experimenting with customizations, I had to add more because many libraries having a different import than its name.
If relevant I can share or open the relevant PR.

I also noticed some performance issues, running on a fairly large project it was unbearable, it is now better. If relevant I can open the PR with those changes too

**Comment by Arkq** [comment]
If you have some improvements, bug fixing, etc. you are welcome to create PRs. But please create separate PR for library customizations, and performance improvements.
