### ISSUE TITLE
Beyond max depth

### ISSUE THREAD

**Issue by Dreamsorcerer** [Arkq/flake8-requirements#43]
It seems that flake8-requirements will only parse a `-r requirements` one level deep?

This is therefore throwing an error while trying it out on the aiohttp repository. Would be nice to have this enabled.
See: https://github.com/aio-libs/aiohttp/pull/5934/checks?check_run_id=3269519740

**Comment by Arkq** [comment]
See the last paragraph of the README file.

**Comment by Dreamsorcerer** [comment]
Ah, sorry, that's perfect.

**Comment by Dreamsorcerer** [comment]
Although maybe it's possible to mention the configuration option in the error message?
