### ISSUE TITLE
Provide package via conda-forge

### ISSUE THREAD

**Issue by joburm** [Arkq/flake8-requirements#49]
Are you considering making the package available on conda-forge? Would be nice to have it there.

**Comment by Arkq** [comment]
I'm not familiar with conda-forge. If there is a way of uploading package there via github actions (like this: https://github.com/Arkq/flake8-requirements/blob/master/.github/workflows/pythonpublish.yml) I might add it as well. But currently I've got rather no time for research, so I will add that only if someone will provide a PR or at least a simple copy-paste example in some other repository.

**Comment by joburm** [comment]
Unfortunately, I don't have experience with publishing on conda-forge. As far as I understood one has to fork the repo [/conda-forge/staged-recipes](https://github.com/conda-forge/staged-recipes), add a so called conda recipe and create a pull request. Then the PR will be reviewed by the conda-forge team and after approval a feedstock repo will be created automatically which provides the package for conda-forge. If the package gets updated on pypi the feedstock repo should be updated as well to provide the new version to conda-forge. I read that the conda-forge team implemented an automatism that creates a PR to the feedstock repo with the updated version from pypi in case of an updates on pypi. So the conda-forge package maintainer ideally only has to approve this PR.
Thus, the main effort probably lies in creating the initial conda recipe. This could be done automatically with [grayskull](https://github.com/conda-incubator/grayskull). But that seems to require an sdist being published to pypi, which is not the case for this package here. 
Since I do not really have the time to do further research, I created a new package request issue /conda-forge/staged-recipes#18750 within conda-forge's repo where it probably fits better. I think this issue here could be closed then.
