### ISSUE TITLE
tool.flake8.known-modules namespace issues

### ISSUE THREAD

**Issue by jonyscathe** [Arkq/flake8-requirements#58]
Hi,

Just moved over to usingflake8-pyproject and `[tool.flake8.known-modules]` looks like a great addition for that.

Did take me a while to get it working though, due to the use of a namespace in the project.

My previous `known-modules` from setup.cfg was of the form:

`known-modules = my_namespace.my_project:[my_namespace.my_project, packaging, dunamai]`

I attempted to change to this but was getting a whole lot of I900s flagged:
```
[tool.flake8.known-modules]
my_namespace.my_project = [
    'my_namespace.my_project',
    'packaging',
    'dunamai',
]
```

Eventually I worked out that I could change to:
```
[tool.flake8.known-modules]
'my_namespace.my_project' = [
    'my_namespace.my_project',
    'packaging',
    'dunamai',
]
```
It looks a little gross with the key in quotes but it at least works. I'm not sure there is any way around this? If not, might be worth adding a short note to the documentation as otherwise this could confuse a few people.

**Comment by Arkq** [comment]
> It looks a little gross with the key in quotes but it at least works. I'm not sure there is any way around this? 

Maybe @nyuszika7h can say more about this, I'm not using pyproject as for now.
