### ISSUE TITLE
Update toml dependency

### ISSUE THREAD

**Issue by mwgamble** [arkq/flake8-requirements#70]
The `toml` package is unmaintained. The `tomli` package is used by many other code quality tools in the Python ecosystem. As it was used as the basis for the `tomllib` standard library package added to Python 3.11, it would be good to use `tomli`. A conditional dependency could be added, so that users on Python 3.11 don't need to install the additional dependency.

I'm happy to submit a PR for this if you'd like.

**Comment by arkq** [comment]
> I'm happy to submit a PR for this if you'd like.

Yes please
