### ISSUE TITLE
python-on-whales not recognised

### ISSUE THREAD

**Issue by Dreamsorcerer** [arkq/flake8-requirements#74]
If python-on-whales appears in the requirements file, it still produces an error when importing python_on_whales.
Does the library only replace 1 `-` with `_` when comparing or something?

**Comment by arkq** [comment]
> Does the library only replace 1 - with _ when comparing or something?

No, but it strips "python_" prefix completely... This package is a rare case where the "python_" prefix is in the module name. I'll try to fix that.
