### ISSUE TITLE
Broken Python2 support

### ISSUE THREAD

**Issue by iivanov-qb** [arkq/flake8-requirements#75]
https://github.com/arkq/flake8-requirements/pull/72 unintentionally broke the Python2 support, as tomli supports only Python3. Version 1.7.5 of flake8-requirements still works fine on Python2. 

I see that you are preparing version 2.0 which officially removes the Python2 support, but I think that it is still good idea to create v1.7.9, fixing the Python2 support, conditionally using toml for Python2 and tomli for Python3. As now, whoever tries to install flake8-requirements for Python2 will end up with error, as pip would take v1.7.8, which is marked as Python2 supporting, but is already broken. 

I could help with a PR, if you think it is a good idea to do this.

**Comment by arkq** [comment]
Ooo I see. If you can provide a PR (or a diff attached to that issue) I'll be glad. I'm afraid I won't be able to test things with python2.... I will create a bug fix release.
