### ISSUE TITLE
Check I901: required but not used dependencies was never implemented

### ISSUE THREAD

**Issue by iivanov-qb** [arkq/flake8-requirements#76]
This check is documented, but was never implemented. This is extremely misleading for the users, as they are relying on the described functionality.

Till the check is implemented, it's absence should be properly documented.

**Comment by arkq** [comment]
Is such note sufficient: https://github.com/arkq/flake8-requirements/pull/77 ?

Or maybe I should not mention I901 at all... The current status of this check is that it requires some changes in the flake8 itself to be "production ready". Unfortunately, I've got no time to propose any changes to the flake8 core project.

For anyone reading this. The problem with this check is that the file where dependencies are stored is: a) not a python file, b) it has to be checked as the last file (so before the check we can gather all used imports). As for now, flake8 does not provide any "finalize" API call. I've managed to hack such functionality, but it requires flake8 monkey-patching which I do not want to put as a "production ready" solution. The WIP is here: https://github.com/arkq/flake8-requirements/tree/901
