### ISSUE TITLE
poetry and `pyproject.toml` support

### ISSUE THREAD

**Issue by sobolevn** [Arkq/flake8-requirements#8]
Hello! Thanks a lot for your plugin. It is awesome!

Do you have any plans in supporting `poetry` and `pyproject.toml`?

**Comment by Arkq** [comment]
Hi, I was not aware, that there are some other packet manages :) Looking at the home pages of these manages, it seems that support for them should be rather easy, so when I find some spare time  I'll try to support them.

**Comment by sobolevn** [comment]
Awesome! If so, I would be happy to include this linter into https://github.com/wemake-services/wemake-django-template
