### ISSUE TITLE
Request: adding default `--requirements-file` to args

### ISSUE THREAD

**Issue by jamesbraza** [arkq/flake8-requirements#80]
From `flake8-requirements==2.0.1`'s `--help`:

```none
  --requirements-file REQUIREMENTS_FILE
                        Specify the name (location) of the requirements text file. Unless an absolute path is given, the file will be searched relative to the project's root directory. If this option is given,
                        requirements from setup.py, setup.cfg or pyproject.toml will not be taken into account.
```

It would be useful to include the default behavior for `--requirements-file` in the help description. Thank you in advance

**Comment by arkq** [comment]
> It would be useful to include the default behavior for `--requirements-file` in the help description.

What do you mean by that? Is this description not accurate?

**Comment by jamesbraza** [comment]
Oh thanks for asking for clarification. I guess, reading the current help text, it doesn't mention that `requirements.txt` is one of the default routes.  So I think something like this:

```diff
--- requirements from setup.py, setup.cfg or pyproject.toml
+++ requirements from requirements.txt, setup.py, setup.cfg or pyproject.toml
```

If you like it, happy to open a PR for this

**Comment by arkq** [comment]
Yes, please submit a PR
