### ISSUE TITLE
Bug / question: why `tomli` dependency?

### ISSUE THREAD

**Issue by jamesbraza** [arkq/flake8-requirements#85]
https://github.com/arkq/flake8-requirements/commit/0e3b5fc1211b93e5e62fe955aac2e4500c1d7a0e added `toml` as a dependency, which was later updated to `tomli` in https://github.com/arkq/flake8-requirements/commit/978e2057656adf6f2b05dd554d79dc22a372c9a6.

Since `flake8` itself doesn't integrate with TOML, why is `toml`/`tomli` a dependency of `flake8-requirements`? It seems unused:

```bash
git clone git@github.com:arkq/flake8-requirements.git
cd flake8-requirements
pip install -e .
pip uninstall -y tomli
python setup.py pytest
# All tests pass
```

**Comment by arkq** [comment]
TOML support is required for `pyproject.toml` parsing. This library is required for python < 3.11

> python setup.py pytest
> # All tests pass

pytest setups test environment so it installs all missing packages (in that case tomli in case of python < 3.11)

**Comment by jamesbraza** [comment]
> TOML support is required for `pyproject.toml` parsing

This is true in general, but there's no `pyproject.toml` in this repo, and there's no `pyproject.toml` support for `flake8` unless `Flake8-requirements` was installed (in which case, it manages [its own TOML dependency](https://github.com/john-hen/Flake8-pyproject/blob/1.2.3/pyproject.toml#L22-L23)).

Also, `pytest` is a development-time dependency, and thus it's not needed to be installed as a required dependency of `flake8-requirements`.

Also, when one runs `python setup.py pytest`, fwiw it actually does not install `toml`/`tomli`.

**Comment by arkq** [comment]
> (in which case, Flake8-pyproject manages [its own TOML dependency](https://github.com/john-hen/Flake8-pyproject/blob/1.2.3/pyproject.toml#L22-L23))

Yes, but flake8-requirements uses libtoml:
https://github.com/arkq/flake8-requirements/blob/master/src/flake8_requirements/checker.py#L15
https://github.com/arkq/flake8-requirements/blob/master/src/flake8_requirements/checker.py#L552

So, it HAS TO be a direct dependency of flake8-requirements. It also shall be a direct dependency of flake8-pyproject. Dependencies are not transitive, every project shall define its own direct dependencies.

**Comment by jamesbraza** [comment]
Oh ha you're right it's actually used, nevermind to this.

We should run `flake8-requirements` on itself in CI, it could have prevented me from opening that PR.  See: https://github.com/arkq/flake8-requirements/pull/87
