### ISSUE TITLE
Feature request: Add support for dynamic dependencies

### ISSUE THREAD

**Issue by miAndreev** [arkq/flake8-requirements#90]
Hi,
I am migrating to dynamic value of dependencies section(in setuptools). So I found that this variant isn't supported by the plugin.
Do you plan to add it?
If not I can try to implement it.

**Comment by arkq** [comment]
> Do you plan to add it?

Currently. I'm not developing this project actively any more. However, I'm reviewing and merging PRs, so, please implement it ans submit a PR :)

**Comment by miAndreev** [comment]
Hi,
I have extended the code and I have added tests for the code.
The PR is https://github.com/arkq/flake8-requirements/pull/91.
I haven't changed the version as I don't know how do you like to bump the version

**Comment by nightwatch92** [comment]
Hi,
when this change is going to be released ?

**Comment by arkq** [comment]
> when this change is going to be released ?

Sorry, I was off on a holiday. I'll try to merge the PR and release it today.
